version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: "%(levelname)s:%(name)s:%(message)s"
  only_msg:
    format: "%(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: only_msg
    filename: tree.log
loggers:
  lexer:
    level: DEBUG
    handlers: [console]
  parser:
    level: DEBUG
    handlers: [console]
  tree:
    level: DEBUG
    handlers: [file]
